### ISSUE TITLE
Fix all recent spec flakiness

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1013]
Specs on CI have become flaky in the last two weeks.

Gather a list of all flaky specs and fix them.

<details>
<summary>
source code browsing -- source-tree -- allows navigating the tree structure (failed)
</summary>

![source code browsing -- source-tree -- allows navigating the tree structure (failed)](https://user-images.githubusercontent.com/158411/95595171-2afdcb00-0a4c-11eb-9747-6d44f8a11a6f.png)

```
1) source code browsing
--
  | source-tree
  | allows navigating the tree structure:
  | CypressError: Timed out retrying: `cy.click()` failed because this element is detached from the DOM.
  |  
  | `<svg data-cy="expand-this" style="flex-shrink: 0;" width="24" height="24" fill="var(--color-foreground-level-5)" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">...</svg>`
  |  
  | Cypress requires elements be attached in the DOM to interact with them.
  |  
  | The previous command that ran was:
  |  
  | > `cy.get()`
  |  
  | This DOM element likely became detached somewhere between the previous and current command.
  |  
  | Common situations why this happens:
  | - Your JS framework re-rendered asynchronously
  | - Your app code reacted to an event firing and removed the element
  |  
  | You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.
  |  
  | https://on.cypress.io/element-has-detached-from-dom
  | at $Cy.ensureAttached (http://localhost:46013/__cypress/runner/cypress_runner.js:159890:24)
  | at runAllChecks (http://localhost:46013/__cypress/runner/cypress_runner.js:148951:12)
  | at retryActionability (http://localhost:46013/__cypress/runner/cypress_runner.js:149010:16)
  | at tryCatcher (http://localhost:46013/__cypress/runner/cypress_runner.js:9956:23)
  | at Function.Promise.attempt.Promise.try (http://localhost:46013/__cypress/runner/cypress_runner.js:7230:29)
  | at tryFn (http://localhost:46013/__cypress/runner/cypress_runner.js:163121:24)
  | at whenStable (http://localhost:46013/__cypress/runner/cypress_runner.js:163162:12)
  | at http://localhost:46013/__cypress/runner/cypress_runner.js:162685:16
  | at tryCatcher (http://localhost:46013/__cypress/runner/cypress_runner.js:9956:23)
  | at Promise._settlePromiseFromHandler (http://localhost:46013/__cypress/runner/cypress_runner.js:7891:31)
  | at Promise._settlePromise (http://localhost:46013/__cypress/runner/cypress_runner.js:7948:18)
  | at Promise._settlePromise0 (http://localhost:46013/__cypress/runner/cypress_runner.js:7993:10)
  | at Promise._settlePromises (http://localhost:46013/__cypress/runner/cypress_runner.js:8073:18)
  | at Promise._fulfill (http://localhost:46013/__cypress/runner/cypress_runner.js:8017:18)
  | at http://localhost:46013/__cypress/runner/cypress_runner.js:9631:46
  | From Your Spec Code:
  | at Context.eval (http://localhost:46013/__cypress/tests?p=cypress/integration/project_source_browsing.spec.js:252:40)
  |  
  |  
  |  
  |  
  | (Results)
  |  
  | ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  | │ Tests:        23                                                                               │
  | │ Passing:      20                                                                               │
  | │ Failing:      1                                                                                │
  | │ Pending:      2                                                                                │
  | │ Skipped:      0                                                                                │
  | │ Screenshots:  1                                                                                │
  | │ Video:        false                                                                            │
  | │ Duration:     25 seconds                                                                       │
  | │ Spec Ran:     project_source_browsing.spec.js                                                  │
  | └────────────────────────────────────────────────────────────────────────────────────────────────┘
  |  
```
</details>

<details>
<summary>
source code browsing -- source-tree -- when clicking on a file name -- for non-binary files -- shows the contents of the file (failed)
</summary>

![source code browsing -- source-tree -- when clicking on a file name -- for non-binary files -- shows the contents of the file (failed)](https://user-images.githubusercontent.com/158411/95595855-f2122600-0a4c-11eb-8bde-6aea04a6a661.png)

```

1) source code browsing
--
  | page view
  | when we're looking at the project root
  | when there is a README file
  | shows the README file:
  | CypressError: Timed out retrying: `cy.click()` failed because this element is detached from the DOM.
  |  
  | `<a class="file svelte-kd57qy" href="#/projects/rad:git:hwd1yred3rwz6y4hw8cz76kw7wean7148jiyduo4bhige81xafqe3jtj8sh/source">...</a>`
  |  
  | Cypress requires elements be attached in the DOM to interact with them.
  |  
  | The previous command that ran was:
  |  
  | > `cy.contains()`
  |  
  | This DOM element likely became detached somewhere between the previous and current command.
  |  
  | Common situations why this happens:
  | - Your JS framework re-rendered asynchronously
  | - Your app code reacted to an event firing and removed the element
  |  
  | You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.
  |  
  | https://on.cypress.io/element-has-detached-from-dom
  | at $Cy.ensureAttached (http://localhost:43517/__cypress/runner/cypress_runner.js:159890:24)
  | at runAllChecks (http://localhost:43517/__cypress/runner/cypress_runner.js:148951:12)
  | at retryActionability (http://localhost:43517/__cypress/runner/cypress_runner.js:149010:16)
  | at tryCatcher (http://localhost:43517/__cypress/runner/cypress_runner.js:9956:23)
  | at Function.Promise.attempt.Promise.try (http://localhost:43517/__cypress/runner/cypress_runner.js:7230:29)
  | at tryFn (http://localhost:43517/__cypress/runner/cypress_runner.js:163121:24)
  | at whenStable (http://localhost:43517/__cypress/runner/cypress_runner.js:163162:12)
  | at http://localhost:43517/__cypress/runner/cypress_runner.js:162685:16
  | at tryCatcher (http://localhost:43517/__cypress/runner/cypress_runner.js:9956:23)
  | at Promise._settlePromiseFromHandler (http://localhost:43517/__cypress/runner/cypress_runner.js:7891:31)
  | at Promise._settlePromise (http://localhost:43517/__cypress/runner/cypress_runner.js:7948:18)
  | at Promise._settlePromise0 (http://localhost:43517/__cypress/runner/cypress_runner.js:7993:10)
  | at Promise._settlePromises (http://localhost:43517/__cypress/runner/cypress_runner.js:8073:18)
  | at Promise._fulfill (http://localhost:43517/__cypress/runner/cypress_runner.js:8017:18)
  | at http://localhost:43517/__cypress/runner/cypress_runner.js:9631:46
  | From Your Spec Code:
  | at Context.eval (http://localhost:43517/__cypress/tests?p=cypress/integration/project_source_browsing.spec.js:132:58)


```
</details>

<details>
<summary>
source code browsing -- page view -- when we're looking at the project root -- when there is a README file -- shows the README file (failed)
</summary>

![source code browsing -- page view -- when we're looking at the project root -- when there is a README file -- shows the README file (failed)](https://user-images.githubusercontent.com/158411/95595954-1241e500-0a4d-11eb-9c34-b6db615d81cf.png)

```
2) source code browsing
  | source-tree
  | when clicking on a file name
  | for non-binary files
  | shows the contents of the file:
  | CypressError: Timed out retrying: `cy.click()` failed because this element is detached from the DOM.
  |  
  | `<svg data-cy="expand-src" style="flex-shrink: 0;" width="24" height="24" fill="var(--color-foreground-level-5)" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">...</svg>`
  |  
  | Cypress requires elements be attached in the DOM to interact with them.
  |  
  | The previous command that ran was:
  |  
  | > `cy.get()`
  |  
  | This DOM element likely became detached somewhere between the previous and current command.
  |  
  | Common situations why this happens:
  | - Your JS framework re-rendered asynchronously
  | - Your app code reacted to an event firing and removed the element
  |  
  | You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.
  |  
  | https://on.cypress.io/element-has-detached-from-dom
  | at $Cy.ensureAttached (http://localhost:43517/__cypress/runner/cypress_runner.js:159890:24)
  | at runAllChecks (http://localhost:43517/__cypress/runner/cypress_runner.js:148951:12)
  | at retryActionability (http://localhost:43517/__cypress/runner/cypress_runner.js:149010:16)
  | at tryCatcher (http://localhost:43517/__cypress/runner/cypress_runner.js:9956:23)
  | at Function.Promise.attempt.Promise.try (http://localhost:43517/__cypress/runner/cypress_runner.js:7230:29)
  | at tryFn (http://localhost:43517/__cypress/runner/cypress_runner.js:163121:24)
  | at whenStable (http://localhost:43517/__cypress/runner/cypress_runner.js:163162:12)
  | at http://localhost:43517/__cypress/runner/cypress_runner.js:162685:16
  | at tryCatcher (http://localhost:43517/__cypress/runner/cypress_runner.js:9956:23)
  | at Promise._settlePromiseFromHandler (http://localhost:43517/__cypress/runner/cypress_runner.js:7891:31)
  | at Promise._settlePromise (http://localhost:43517/__cypress/runner/cypress_runner.js:7948:18)
  | at Promise._settlePromise0 (http://localhost:43517/__cypress/runner/cypress_runner.js:7993:10)
  | at Promise._settlePromises (http://localhost:43517/__cypress/runner/cypress_runner.js:8073:18)
  | at Promise._fulfill (http://localhost:43517/__cypress/runner/cypress_runner.js:8017:18)
  | at http://localhost:43517/__cypress/runner/cypress_runner.js:9631:46
  | From Your Spec Code:
  | at Context.eval (http://localhost:43517/__cypress/tests?p=cypress/integration/project_source_browsing.spec.js:292:47)
  |  
 


```
</details>

**Comment by rudolfs** [comment]
This seems to be gone now.
