### ISSUE TITLE
Can't load projects with duplicate branches

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1292]
Steps to reproduce:

1. `yarn reset:state`, start Upstream
2. follow this project from seedling: `rad:git:hwd1yreg4q3sjjhj965enak5obbnf7og7e851csa3wp1ycaq7pccncwem4h`
3. navigate to the project in the "Following" tab

**Expected**: to see the project source
**Actual**: only see the project header and an error in the console

**Note**: I was expecting to see the error as a copyable error notification, but it only showed up in the console. The app locked up and was only usable after navigating away from the broken project *and* a manual refresh.

When inspecting the API requests, it looks like we're replicating projects that have multiple branches with the same name:
```
GET http://localhost:17246/v1/source/branches/rad:git:hwd1yreg4q3sjjhj965enak5obbnf7og7e851csa3wp1ycaq7pccncwem4h?peerId=hybn7bi7m95qbm47hto73tp4riqokq5jj3iz9egjjjq5i318zqyxaa

["fintan","fintan","master","reset"]
```

```
error.ts:52 An unexpected error occured {code: "UnhandledRejection", source: {…}}code: "UnhandledRejection"source: code: "UnknownException"details: {name: "Error"}message: "Cannot have duplicate keys in a keyed each"stack: "Error: Cannot have duplicate keys in a keyed each
    at validate_each_keys (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:982:23)
    at Array.create_default_slot$1d (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:38021:6)
    at create_slot (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:63:33)
    at create_fragment$1f (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:23681:27)
    at init (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:1112:41)
    at new Overlay (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:23823:7)
    at create_fragment$1P (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:38161:16)
    at init (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:1112:41)
    at new RevisionSelector (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:38312:7)
    at Array.create_left_slot$3 (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:63531:25)"__proto__: Object__proto__: Object
log @ error.ts:52
show$1 @ error.ts:57
(anonymous) @ error.ts:99
index.mjs:1207 Uncaught (in promise) Error: Cannot have duplicate keys in a keyed each
    at validate_each_keys (index.mjs:1207)
    at Array.create_default_slot$1d (RevisionSelector.svelte:99)
    at create_slot (index.mjs:61)
    at create_fragment$1f (overlay.ts:12)
    at init (index.mjs:1476)
    at new Overlay (Overlay.svelte:17)
    at create_fragment$1P (RevisionSelector.svelte:99)
    at init (index.mjs:1476)
    at new RevisionSelector (RevisionSelector.svelte:103)
    at Array.create_left_slot$3 (Commits.svelte:6)
```

<img width="1552" alt="Screenshot 2020-11-20 at 06 39 18" src="https://user-images.githubusercontent.com/158411/99763425-20c6f600-2afb-11eb-90e4-4617b6211964.png">

**Comment by xla** [comment]
The layout of the project on the seed looks as follows:

```
/state/git/refs/namespaces/hwd1yreg4q3sjjhj965enak5obbnf7og7e851csa3wp1ycaq7pccncwem4h/
└── refs
    ├── rad
    │   ├── id
    │   ├── ids
    │   │   └── hwd1yreyixbxac8n71ahfkhj1jwf8xtqgjxw15fqdf8whzpau5hkh9kg48w
    │   └── signed_refs
    └── remotes
        └── hybn7bi7m95qbm47hto73tp4riqokq5jj3iz9egjjjq5i318zqyxaa
            ├── heads
            │   ├── fintan
            │   │   ├── tracking-docs
            │   │   └── urn-context-patch
            │   ├── master
            │   └── reset
            └── rad
                ├── id
                ├── ids
                │   └── hwd1yreyixbxac8n71ahfkhj1jwf8xtqgjxw15fqdf8whzpau5hkh9kg48w
                ├── self
                └── signed_refs
```

The branches we see surfacing aren't duplicates but namespaced and somewhere along the way the parts behind the slash et lost.

**Comment by rudolfs** [comment]
And locally when followed in Upstream:
```
/Users/rudolfs/Library/Application\ Support/xyz.radicle.radicle/git/refs/namespaces/hwd1yreg4q3sjjhj965enak5obbnf7og7e851csa3wp1ycaq7pccncwem4h
└── refs
    ├── rad
    │   ├── id
    │   ├── ids
    │   │   └── hwd1yreyixbxac8n71ahfkhj1jwf8xtqgjxw15fqdf8whzpau5hkh9kg48w
    │   ├── self
    │   └── signed_refs
    └── remotes
        ├── hybn7bi7m95qbm47hto73tp4riqokq5jj3iz9egjjjq5i318zqyxaa
        │   ├── heads
        │   │   ├── fintan
        │   │   │   ├── tracking-docs
        │   │   │   └── urn-context-patch
        │   │   ├── master
        │   │   └── reset
        │   └── rad
        │       ├── id
        │       ├── ids
        │       │   └── hwd1yreyixbxac8n71ahfkhj1jwf8xtqgjxw15fqdf8whzpau5hkh9kg48w
        │       ├── self
        │       └── signed_refs
        └── hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw
            └── rad
                ├── id
                └── ids
                    └── hwd1yreyixbxac8n71ahfkhj1jwf8xtqgjxw15fqdf8whzpau5hkh9kg48w
```
