### ISSUE TITLE
Branch names containing `+` or `&` break source screen

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1383]
To reproduce: create a repository with a branch named `ampersands&work` or `plus+works`, create a new project with this repository and select that branch in the revision selector. Or use this [repo](https://github.com/rudolfs/repo-from-hell).

```json
{
  "code": "RemoteStoreError",
  "message": "Internal Git error: reference 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/ampersands' not found; class=Reference (4); code=NotFound (-3)",
  "source": {
    "code": "UnknownException",
    "message": "Internal Git error: reference 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/ampersands' not found; class=Reference (4); code=NotFound (-3)",
    "stack": "Error: Internal Git error: reference 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/ampersands' not found; class=Reference (4); code=NotFound (-3)\n    at http (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:3438:19)\n    at async fetchTreeCode (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:57198:30)\n    at async Promise.all (index 1)\n    at async selectRevision (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:57210:55)",
    "details": {
      "response": {},
      "name": "Error"
    }
  }
}
```

<img width="1552" alt="Screenshot 2020-11-26 at 13 32 47" src="https://user-images.githubusercontent.com/158411/100351582-f1792300-2feb-11eb-9406-edede188f7d6.png">

```json
{
  "code": "RemoteStoreError",
  "message": "Internal Git error: the given reference name 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/plus works' is not valid; class=Reference (4); code=InvalidSpec (-12)",
  "source": {
    "code": "UnknownException",
    "message": "Internal Git error: the given reference name 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/plus works' is not valid; class=Reference (4); code=InvalidSpec (-12)",
    "stack": "Error: Internal Git error: the given reference name 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/plus works' is not valid; class=Reference (4); code=InvalidSpec (-12)\n    at http (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:3438:19)\n    at async Promise.all (index 0)\n    at async selectRevision (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:57210:55)",
    "details": {
      "response": {},
      "name": "Error"
    }
  }
}
```
<img width="1552" alt="Screenshot 2020-11-26 at 13 35 45" src="https://user-images.githubusercontent.com/158411/100351792-4d43ac00-2fec-11eb-8fe3-c41fc9e39f50.png">

**Comment by xla** [comment]
This looks like the query param is not escaped properly as it cuts of after the `&` and likely sends the `works` as distinct bool param. Could you show what the request looks like in the network tab for this?

**Comment by rudolfs** [comment]
Request headers:
```
GET /v1/source/commits/rad:git:hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/?revision%5Btype%5D=branch&revision%5Bname%5D=ampersands%26work&revision%5BpeerId%5D=hynfh7ogti38wrrdnzmayow683tsrrzq94timregr8rzmwsdn3aijw HTTP/1.1
Host: localhost:17246
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RadicleUpstream/0.1.2 Chrome/87.0.4280.67 Electron/11.0.2 Safari/537.36
Content-Type: application/json
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB
Cookie: auth-token=d5cde14b5bfcad5354f2c4859894214125f583d25bae025fa0cb117f5ca88568
```
Response:
```
{"message":"Internal Git error: reference 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/ampersands' not found; class=Reference (4); code=NotFound (-3)","variant":"GIT_ERROR"}
```

**Comment by xla** [comment]
Looks like the UI is sending it correctly, but the API is not using the ampersede_decoding:

https://github.com/radicle-dev/radicle-upstream/blob/c77ea9dfd121c1d8e2f3448212c2a7005968335e/proxy/api/src/http/source.rs#L39

All other endpoints in there use our own querystiring infrastructure.

**Comment by FintanH** [comment]
Can we just change all `query` to `with_qs` because warp's query function just doesn't do what we'd like, unfortunately?

**Comment by FintanH** [comment]
The issue here is that we have the following code:
https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/api/src/http.rs#L180-L183

The `raw` string comes in the form:
```
peerId=hybaapjdrhj8mg4mathpwjaeuktfzxd8uqfpjknp65fyncehpxxzze&revision%5Btype%5D=branch&revision%5Bname%5D=ampersands%26work&revision%5BpeerId%5D=hybaapjdrhj8mg4mathpwjaeuktfzxd8uqfpjknp65fyncehpxxzze&prefix=
```

focusing on the `revision` declaration, this string gets decoded into
```
revision[type]=branch&revision[name]=ampersands&work&revision[peerId]=hybaapjdrhj8mg4mathpwjaeuktfzxd8uqfpjknp65fyncehpxxzze
```

which we then attempt to deserialize into a `Revision`. However, note that the `amersands%26work` also got decoded into `amersands&work`. This means that this is viewed as a URL component by `serde_qs`.
