### ISSUE TITLE
Branch names containing "+" break source screen

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#1384]
To reproduce: create a repository with a branch named `plus+works`, create a new project with this repository and select that branch in the revision selector.

```json
{
  "code": "RemoteStoreError",
  "message": "Internal Git error: the given reference name 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/plus works' is not valid; class=Reference (4); code=InvalidSpec (-12)",
  "source": {
    "code": "UnknownException",
    "message": "Internal Git error: the given reference name 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/plus works' is not valid; class=Reference (4); code=InvalidSpec (-12)",
    "stack": "Error: Internal Git error: the given reference name 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/plus works' is not valid; class=Reference (4); code=InvalidSpec (-12)\n    at http (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:3438:19)\n    at async Promise.all (index 0)\n    at async selectRevision (file:///Users/rudolfs/work/radicle-upstream/public/bundle.js:57210:55)",
    "details": {
      "response": {},
      "name": "Error"
    }
  }
}
```
<img width="1552" alt="Screenshot 2020-11-26 at 13 35 45" src="https://user-images.githubusercontent.com/158411/100351792-4d43ac00-2fec-11eb-8fe3-c41fc9e39f50.png">

**Comment by xla** [comment]
https://github.com/radicle-dev/radicle-upstream/issues/1383#issuecomment-734274582

**Comment by rudolfs** [comment]
<details>
<summary>Failed request 1</summary>

- Request headers:
```
GET /v1/source/commits/rad:git:hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/?revision%5Btype%5D=branch&revision%5Bname%5D=plus%2Bworks&revision%5BpeerId%5D=hynfh7ogti38wrrdnzmayow683tsrrzq94timregr8rzmwsdn3aijw HTTP/1.1
Host: localhost:17246
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RadicleUpstream/0.1.2 Chrome/87.0.4280.67 Electron/11.0.2 Safari/537.36
Content-Type: application/json
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB
Cookie: auth-token=d5cde14b5bfcad5354f2c4859894214125f583d25bae025fa0cb117f5ca88568
```

- Response:
```
{"message":"Internal Git error: the given reference name 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/plus works' is not valid; class=Reference (4); code=InvalidSpec (-12)","variant":"GIT_ERROR"}
```
</details>

<details>
<summary>Failed request 2</summary>

- Request headers:
```
GET /v1/source/tree/rad:git:hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o?peerId=hynfh7ogti38wrrdnzmayow683tsrrzq94timregr8rzmwsdn3aijw&revision%5Btype%5D=branch&revision%5Bname%5D=plus%2Bworks&revision%5BpeerId%5D=hynfh7ogti38wrrdnzmayow683tsrrzq94timregr8rzmwsdn3aijw&prefix= HTTP/1.1
Host: localhost:17246
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RadicleUpstream/0.1.2 Chrome/87.0.4280.67 Electron/11.0.2 Safari/537.36
Content-Type: application/json
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB
Cookie: auth-token=d5cde14b5bfcad5354f2c4859894214125f583d25bae025fa0cb117f5ca88568
```

- Response:
```
{"message":"Internal Git error: the given reference name 'refs/namespaces/hwd1yreb19gf6bob3r54bc8f3mcy5xe46o4hmo5hcwqcd1ztdjaic1hqt5o/refs/heads/plus works' is not valid; class=Reference (4); code=InvalidSpec (-12)","variant":"GIT_ERROR"}
```
</details>

**Comment by rudolfs** [comment]
Closing in favour of https://github.com/radicle-dev/radicle-upstream/issues/1383.
