### ISSUE TITLE
`git-remote-rad` panics with index out of bounds

### ISSUE THREAD

**Issue by yasushisakai** [radicle-dev/radicle-upstream#1466]
`git-remote-rad` panics showing a rust error. did a quick search on issues but could not spot one.

```
➜ git-remote-rad
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/rudolfs/.cargo/git/checkouts/radicle-link-009c17032bc5eda9/308d2dd/git-helpers/src/remote_helper.rs:46:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
my environment:
- mac os 10.15.7
- rustc 1.48.0 (7eac88abb 2020-11-16)
- Radicule Upstream 0.1.4

It seems that it is trying to access `/Users/rudolfs` directory??

following is the same with `BACKTRACE=full`
<details>

```
➜ RUST_BACKTRACE=full git-remote-rad
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/rudolfs/.cargo/git/checkouts/radicle-link-009c17032bc5eda9/308d2dd/git-helpers/src/remote_helper.rs:46:9
stack backtrace:
   0:        0x1054a4204 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb144aff6cb2709e
   1:        0x1054c3c60 - core::fmt::write::h0ce880d33cd2a300
   2:        0x1054a0596 - std::io::Write::write_fmt::h2bb1b1639b8478a0
   3:        0x1054a5d6f - std::panicking::default_hook::{{closure}}::hb543bf3b05c8104b
   4:        0x1054a5a3d - std::panicking::default_hook::h7015a8c764df2477
   5:        0x1054a633b - std::panicking::rust_panic_with_hook::hb4c39ab085f5a3ba
   6:        0x1054a5ebb - std::panicking::begin_panic_handler::{{closure}}::h85978c5141656d56
   7:        0x1054a4678 - std::sys_common::backtrace::__rust_end_short_backtrace::hba09eb580b3852d8
   8:        0x1054a5e7a - _rust_begin_unwind
   9:        0x1054cf43f - core::panicking::panic_fmt::h33aee6f32da9c3a4
  10:        0x1054cf406 - core::panicking::panic_bounds_check::h5595a3f66ac4adf4
  11:        0x10539cf2a - radicle_git_helpers::remote_helper::run::hf7999182ff7790fe
  12:        0x10536b34a - std::sys_common::backtrace::__rust_begin_short_backtrace::h8ebc4690f423c540
  13:        0x10536b3c1 - std::rt::lang_start::{{closure}}::hc0fde106c18ae591
  14:        0x1054a66b4 - std::rt::lang_start_internal::h5e1feb19f4099625
  15:        0x10536b399 - _main
```

</details>

**Comment by rudolfs** [comment]
`git-remote-rad` isn't supposed to be run stand-alone from the CLI. It's executed by the git tooling when doing a `git push rad`.

That being said, the error message certainly could be improved :)

Read more about git remote helpers [here](https://git-scm.com/docs/gitremote-helpers#_description).

**Comment by rudolfs** [comment]
Opened an issue about improving the error message: https://github.com/radicle-dev/radicle-link/issues/471.
