### ISSUE TITLE
Unable to create an identity

### ISSUE THREAD

**Issue by kon3gor** [radicle-dev/radicle-upstream#1496]
I was trying to create an identity, but got this after entering passphrase:
```
{
  "code": "create-identity-failed",
  "message": "Could not create identity",
  "details": {
    "handle": "kon3gor"
  },
  "source": {
    "code": "UnknownException",
    "message": "Failed to fetch",
    "stack": "TypeError: Failed to fetch",
    "details": {
      "name": "TypeError"
    }
  }
}
```
Followed by this (different usernames because I tried different passwords and nicknames)
```
{
  "code": "create-identity-failed",
  "message": "Could not create identity",
  "details": {
    "handle": "eshendo"
  },
  "source": {
    "code": "UnknownException",
    "message": "A key already exists",
    "details": {
      "message": "A key already exists",
      "variant": "KEY_EXISTS"
    }
  }
}
```
And after few more attempts it became this
```
{
  "code": "create-identity-failed",
  "message": "Could not create identity",
  "details": {
    "handle": "kon3gor"
  },
  "source": {
    "code": "UnknownException",
    "message": "Incorrect input",
    "stack": "Error: Incorrect input\n    at un (file:///tmp/.mount_radicljQ30uK/resources/app.asar/public/bundle.js:1:27043)\n    at async yn (file:///tmp/.mount_radicljQ30uK/resources/app.asar/public/bundle.js:1:27513)\n    at async u (file:///tmp/.mount_radicljQ30uK/resources/app.asar/public/bundle.js:12:331027)",
    "details": {
      "response": {},
      "name": "Error"
    }
  }
}
```
How can I fix this?

**Comment by AlexMikhalev** [comment]
I had the same issue, are you using master or pre-packaged?

**Comment by kon3gor** [comment]
@AlexMikhalev  I'am using a file from [here](https://radicle.xyz/downloads.html). I believe it's what u called pre-packaged

**Comment by AlexMikhalev** [comment]
@kon3gor two things helped me - compiling from git master and checking if you have any firewalls blocking communications.

**Comment by imachug** [comment]
I have the same issue. I use Linux, Ubuntu 20.04. I built Upstream 0.1.6 from source. If that matters, I use Node 12.18.2, rustc 1.49.0.

I've repeated the following process several times: run `./scripts/reset-state.sh`, run `yarn start`, try to register. The results are `--+--+-`, where `-` means I get an error (the same all the time):

```json
{
  "code": "create-identity-failed",
  "message": "Could not create identity",
  "details": {
    "handle": "Ivanq"
  },
  "source": {
    "code": "UnknownException",
    "message": "Failed to fetch",
    "stack": "TypeError: Failed to fetch",
    "details": {
      "name": "TypeError"
    }
  }
}
```

...and `+` means I've successfully registered.

The logs for the successful case are:

```
yarn run v1.22.10
$ RADICLE_UPSTREAM_EXPERIMENTAL=false yarn start:app
$ run-p --race rollup:watch proxy:start electron:start
$ yarn rollup:clean && rollup -c -w
$ cd proxy && cargo build --bin git-remote-rad && cargo run
$ wait-on ./public/bundle.js && wait-on ./native/main.comp.js && wait-on tcp:17246 && NODE_ENV=development electron .
$ rm -rf public/bundle.* && rm -f native/main.comp.js
    Finished dev [unoptimized + debuginfo] target(s) in 0.66s
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/radicle-proxy`
 INFO  coco::git_helper > Copied git remote helper to: "/home/ivanq/.radicle/bin/git-remote-rad"
 DEBUG sled::pagecache::snapshot > no previous snapshot found
 DEBUG sled::pagecache::iterator > ordering before clearing tears: {}, max_header_stable_lsn: 0
 DEBUG sled::pagecache::iterator > in clean_tail_tears, found missing item in tail: None and we'll scan segments {} above lowest lsn 0
 DEBUG sled::pagecache::iterator > unable to load new segment: Io(Custom { kind: Other, error: "no segments remaining to iterate over" })
 DEBUG sled::pagecache::iterator > filtering out segments after detected tear at (lsn, lid) -1
 DEBUG sled::pagecache::iterator > unable to load new segment: Io(Custom { kind: Other, error: "no segments remaining to iterate over" })
 DEBUG sled::pagecache::segment  > SA starting with tip 0 stable -1 free {}
 DEBUG sled::pagecache::iobuf    > starting log for a totally fresh system
 DEBUG sled::pagecache::segment  > segment accountant returning offset: 0 for lsn 0 on deck: {}
 DEBUG sled::pagecache::iobuf    > starting IoBufs with next_lsn: 0 next_lid: 0
 DEBUG sled::pagecache::iobuf    > storing lsn 0 in beginning of buffer
 DEBUG sled::pagecache           > load_snapshot loading pages from 0..0
 DEBUG sled::meta                > allocated pid 3 for root of new_tree [95, 95, 115, 108, 101, 100, 95, 95, 100, 101, 102, 97, 117, 108, 116]
 DEBUG sled::pagecache::iobuf    > advancing offset within the current segment from 0 to 71
 INFO  api::process              > starting API
 DEBUG sled::pagecache::iobuf    > wrote lsns 0-70 to disk at offsets 0-70, maxed false complete_len 71
 DEBUG sled::pagecache::iobuf    > mark_interval(0, 71)
 DEBUG sled::pagecache::iobuf    > new highest interval: 0 - 70
 DEBUG sled::pagecache::iobuf    > advancing offset within the current segment from 71 to 96
 DEBUG sled::pagecache::iobuf    > wrote lsns 71-95 to disk at offsets 71-95, maxed false complete_len 25
 DEBUG sled::pagecache::iobuf    > mark_interval(71, 25)
 DEBUG sled::pagecache::iobuf    > new highest interval: 71 - 95
rollup v2.35.1
bundles ui/index.ts → public/bundle.js...
LiveReload enabled
created public/bundle.js in 32.8s
bundles native/main.ts → native/main.comp.js...
created native/main.comp.js in 4.4s

[2021-01-09 00:52:04] waiting for changes...
 DEBUG hyper::proto::h1::io      > read 0 bytes 
 DEBUG hyper::proto::h1::conn    > read eof 
(node:254220) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
 DEBUG hyper::proto::h1::io      > read 409 bytes 
 DEBUG hyper::proto::h1::io      > parsed 10 headers 
 DEBUG hyper::proto::h1::conn    > incoming body is empty 
 DEBUG sled::meta                > allocated pid 5 for root of new_tree [115, 101, 115, 115, 105, 111, 110]
 ERROR api::http::error          > Rejection(NoSession)
 INFO  proxy::http               > "GET /v1/session HTTP/1.1" 404 1.646476ms
 DEBUG hyper::proto::h1::io      > flushed 182 bytes 
 DEBUG sled::pagecache::iobuf    > advancing offset within the current segment from 96 to 164
 DEBUG sled::pagecache::iobuf    > wrote lsns 96-163 to disk at offsets 96-163, maxed false complete_len 68
 DEBUG sled::pagecache::iobuf    > mark_interval(96, 68)
 DEBUG sled::pagecache::iobuf    > new highest interval: 96 - 163

(electron:254220): IBUS-WARNING **: 00:52:08.932: Unable to connect to ibus: Could not connect: Connection refused
 DEBUG hyper::proto::h1::io      > read 456 bytes 
 DEBUG hyper::proto::h1::io      > parsed 11 headers 
 DEBUG hyper::proto::h1::conn    > incoming body is content-length (25 bytes) 
 DEBUG hyper::proto::h1::conn    > incoming body completed 
 DEBUG hyper::server::shutdown   > signal received, starting graceful shutdown 
 INFO  proxy::http               > "POST /v1/keystore HTTP/1.1" 204 14.860811411s
 DEBUG hyper::proto::h1::io      > flushed 180 bytes 
 DEBUG sled::pagecache::logger   > IoBufs dropped
 DEBUG api::process              > aborted
 DEBUG sled::pagecache::snapshot > no previous snapshot found
 DEBUG sled::pagecache::iterator > ordering before clearing tears: {0: 0}, max_header_stable_lsn: 0
 DEBUG sled::pagecache::iterator > in clean_tail_tears, found missing item in tail: None and we'll scan segments {0: 0} above lowest lsn 0
 DEBUG sled::pagecache::iterator > filtering out segments after detected tear at (lsn, lid) 163
 DEBUG sled::pagecache::iterator > hit max_lsn 163 in iterator, stopping
 DEBUG sled::pagecache::snapshot > zeroing the end of the recovered segment at lsn 0 between lids 164 and 524287
 DEBUG sled::pagecache::blob_io  > gc_blobs removing any blob with an lsn above 164
 DEBUG sled::pagecache::segment  > SA starting with tip 524288 stable -1 free {}
 DEBUG sled::pagecache::iobuf    > starting log at recovered active offset 164, recovered lsn 164
 DEBUG sled::pagecache::iobuf    > starting IoBufs with next_lsn: 164 next_lid: 164
 DEBUG sled::pagecache           > load_snapshot loading pages from 0..6
 INFO  librad::net::protocol     > Protocol::run; local.id=hybmoicwwz6diobtkw3zosyq9fsq9i8sdn36tinuni6d3s8pq6kcqn local.addr=0.0.0.0:39894
 INFO  api::process              > starting API
 INFO  api::process              > starting peer
 INFO  librad::net::protocol     > Listening 
 DEBUG sled::meta                > allocated pid 7 for root of new_tree [119, 97, 105, 116, 105, 110, 103, 95, 114, 111, 111, 109]
 INFO  librad::net::protocol     > establishing connection remote.id=hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw remote.addr=34.91.29.42:12345 
 DEBUG coco::peer::subroutines   > handling subroutine input: Protocol(Listening(0.0.0.0:39894))
 DEBUG coco::peer::subroutines   > handling subroutine input: Announce(Tick)
 DEBUG rustls::client::hs        > No cached session for DNSNameRef("hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw")
 DEBUG rustls::client::hs        > Not resuming any session
 DEBUG coco::peer::subroutines   > handling subroutine input: Request(Tick)
 INFO  quinn::connection         > drive; id=0
 DEBUG sled::meta                > allocated pid 9 for root of new_tree [97, 110, 110, 111, 117, 110, 99, 101, 109, 101, 110, 116, 115]
 DEBUG coco::peer::subroutines   > handling subroutine input: Announce(Succeeded({}))
 INFO  quinn::connection         > drive; id=0
 DEBUG quinn_proto::connection   > ECN not acknowledged by peer 
 DEBUG rustls::client::hs        > Using ciphersuite TLS13_CHACHA20_POLY1305_SHA256
 DEBUG rustls::client::tls13     > Not resuming
 DEBUG rustls::client::tls13     > TLS1.3 encrypted extensions: [Protocols([PayloadU8([114, 97, 100, 47, 49])]), ServerNameAck, TransportParameters([1, 4, 128, 0, 253, 232, 3, 4, 128, 0, 255, 228, 4, 4, 128, 152, 150, 128, 5, 4, 128, 19, 18, 208, 6, 4, 128, 19, 18, 208, 7, 4, 128, 19, 18, 208, 8, 1, 32, 9, 1, 32, 11, 1, 0, 14, 1, 5, 64, 182, 0, 2, 16, 107, 97, 208, 235, 126, 176, 174, 80, 86, 117, 238, 46, 182, 0, 55, 118, 32, 4, 128, 0, 255, 255, 0, 20, 245, 247, 213, 182, 235, 168, 188, 41, 137, 91, 219, 251, 91, 32, 224, 14, 22, 13, 127, 36, 15, 8, 55, 111, 14, 178, 163, 33, 171, 48])]
 DEBUG rustls::client::hs        > ALPN protocol is Some([114, 97, 100, 47, 49])
 DEBUG rustls::client::tls13     > Got CertificateRequest CertificateRequestPayloadTLS13 { context: PayloadU8([]), extensions: [SignatureAlgorithms([ECDSA_NISTP384_SHA384, ECDSA_NISTP256_SHA256, ED25519, RSA_PSS_SHA512, RSA_PSS_SHA384, RSA_PSS_SHA256, RSA_PKCS1_SHA512, RSA_PKCS1_SHA384, RSA_PKCS1_SHA256])] }
 DEBUG rustls::client::tls13     > Attempting client auth
 INFO  quinn::connection         > drive; id=0
 INFO  librad::net::protocol     > New outgoing connection remote.id=hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw 
 INFO  tracing::span             > incoming
 INFO  quinn::connection         > drive; id=0
 DEBUG coco::peer::subroutines   > handling subroutine input: Protocol(Connected(PeerId(PublicKey(VerificationKeyBytes("9146828e4f9fa5bcc9eda09e4d194126c021f5072017bf439fe9ef71fc095c1a")))))
 DEBUG coco::peer::sync          > Starting sync from hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw
 DEBUG coco::peer::subroutines   > handling subroutine input: PeerSync(Started(PeerId(PublicKey(VerificationKeyBytes("9146828e4f9fa5bcc9eda09e4d194126c021f5072017bf439fe9ef71fc095c1a")))))
 ERROR coco::peer::subroutines   > sync error for hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw: State(Storage(Config(Unset { config_key: "rad.self" })))
 DEBUG coco::peer::subroutines   > handling subroutine input: PeerSync(Failed(PeerId(PublicKey(VerificationKeyBytes("9146828e4f9fa5bcc9eda09e4d194126c021f5072017bf439fe9ef71fc095c1a")))))
 DEBUG sled::pagecache::iobuf    > advancing offset within the current segment from 164 to 343
 DEBUG sled::pagecache::iobuf    > wrote lsns 164-342 to disk at offsets 164-342, maxed false complete_len 179
 DEBUG sled::pagecache::iobuf    > mark_interval(164, 179)
 DEBUG sled::pagecache::iobuf    > new highest interval: 164 - 342
 INFO  quinn::connection         > drive; id=0
 DEBUG rustls::client::tls13     > Ticket saved
 INFO  quinn::connection         > drive; id=0
 INFO  quinn::connection         > drive; id=0
 DEBUG coco::peer::subroutines   > handling subroutine input: Request(Tick)
 DEBUG hyper::proto::h1::io      > read 536 bytes 
 DEBUG hyper::proto::h1::io      > parsed 12 headers 
 DEBUG hyper::proto::h1::conn    > incoming body is content-length (18 bytes) 
 DEBUG hyper::proto::h1::conn    > incoming body completed 
 INFO  librad::git::storage      > Storage::create_repo; local.id=hybmoicwwz6diobtkw3zosyq9fsq9i8sdn36tinuni6d3s8pq6kcqn
 DEBUG librad::git::storage      > Initial metadata committed repo.urn=rad:git:hwd1yrerkdaarnatnkdecagqnh7fejtdfcbre4sd376jz31ex1x1p9y9whh repo.id.branch=refs/namespaces/hwd1yrerkdaarnatnkdecagqnh7fejtdfcbre4sd376jz31ex1x1p9y9whh/refs/rad/id repo.id.oid=0eb20deee3d00a62dd06d052e121dbdfa96db6fc 
 INFO  librad::git::types        > creating symbolic ref refs/namespaces/hwd1yrerkdaarnatnkdecagqnh7fejtdfcbre4sd376jz31ex1x1p9y9whh/refs/rad/self -> refs/namespaces/hwd1yrerkdaarnatnkdecagqnh7fejtdfcbre4sd376jz31ex1x1p9y9whh/refs/rad/id 
 DEBUG librad::git::storage      > Storage::track_signers local.id=hybmoicwwz6diobtkw3zosyq9fsq9i8sdn36tinuni6d3s8pq6kcqn meta.urn=rad:git:hwd1yrerkdaarnatnkdecagqnh7fejtdfcbre4sd376jz31ex1x1p9y9whh 
 DEBUG librad::git::storage      > Storage::update_refs 
 DEBUG librad::git::storage      > Storage::rad_signed_refs urn=rad:git:hwd1yrerkdaarnatnkdecagqnh7fejtdfcbre4sd376jz31ex1x1p9y9whh 
 DEBUG librad::git::storage      > heads={} 
 DEBUG librad::git::storage      > urn=rad:git:hwd1yrerkdaarnatnkdecagqnh7fejtdfcbre4sd376jz31ex1x1p9y9whh remotes.bare={} 
 DEBUG librad::git::storage      > urn=rad:git:hwd1yrerkdaarnatnkdecagqnh7fejtdfcbre4sd376jz31ex1x1p9y9whh remotes.verified={} 
 INFO  proxy::http               > "POST /v1/identities HTTP/1.1" 201 20.749408ms
 DEBUG hyper::proto::h1::io      > flushed 450 bytes 
 DEBUG sled::pagecache::iobuf    > advancing offset within the current segment from 343 to 892
 DEBUG sled::pagecache::iobuf    > wrote lsns 343-891 to disk at offsets 343-891, maxed false complete_len 549
 DEBUG sled::pagecache::iobuf    > mark_interval(343, 549)
 DEBUG sled::pagecache::iobuf    > new highest interval: 343 - 891
```

The logs at failure:

```
yarn run v1.22.10
$ RADICLE_UPSTREAM_EXPERIMENTAL=false yarn start:app
$ run-p --race rollup:watch proxy:start electron:start
$ yarn rollup:clean && rollup -c -w
$ cd proxy && cargo build --bin git-remote-rad && cargo run
$ wait-on ./public/bundle.js && wait-on ./native/main.comp.js && wait-on tcp:17246 && NODE_ENV=development electron .
  $ rm -rf public/bundle.* && rm -f native/main.comp.js               ] 23/371: bitflags(build.rs), bytes, fnv, proc-macro-nested(build.rs)                 
    Finished dev [unoptimized + debuginfo] target(s) in 0.78s
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/radicle-proxy`
 INFO  coco::git_helper > Copied git remote helper to: "/home/ivanq/.radicle/bin/git-remote-rad"
 DEBUG sled::pagecache::snapshot > no previous snapshot found
 DEBUG sled::pagecache::iterator > ordering before clearing tears: {}, max_header_stable_lsn: 0
 DEBUG sled::pagecache::iterator > in clean_tail_tears, found missing item in tail: None and we'll scan segments {} above lowest lsn 0
 DEBUG sled::pagecache::iterator > unable to load new segment: Io(Custom { kind: Other, error: "no segments remaining to iterate over" })
 DEBUG sled::pagecache::iterator > filtering out segments after detected tear at (lsn, lid) -1
 DEBUG sled::pagecache::iterator > unable to load new segment: Io(Custom { kind: Other, error: "no segments remaining to iterate over" })
 DEBUG sled::pagecache::segment  > SA starting with tip 0 stable -1 free {}
 DEBUG sled::pagecache::iobuf    > starting log for a totally fresh system
 DEBUG sled::pagecache::segment  > segment accountant returning offset: 0 for lsn 0 on deck: {}
 DEBUG sled::pagecache::iobuf    > starting IoBufs with next_lsn: 0 next_lid: 0
 DEBUG sled::pagecache::iobuf    > storing lsn 0 in beginning of buffer
 DEBUG sled::pagecache           > load_snapshot loading pages from 0..0
 DEBUG sled::pagecache::iobuf    > advancing offset within the current segment from 0 to 53
 DEBUG sled::meta                > allocated pid 3 for root of new_tree [95, 95, 115, 108, 101, 100, 95, 95, 100, 101, 102, 97, 117, 108, 116]
 INFO  api::process              > starting API
 DEBUG sled::pagecache::iobuf    > wrote lsns 0-52 to disk at offsets 0-52, maxed false complete_len 53
 DEBUG sled::pagecache::iobuf    > mark_interval(0, 53)
 DEBUG sled::pagecache::iobuf    > new highest interval: 0 - 52
rollup v2.35.1
bundles ui/index.ts → public/bundle.js...
 DEBUG sled::pagecache::iobuf    > advancing offset within the current segment from 53 to 96
 DEBUG sled::pagecache::iobuf    > wrote lsns 53-95 to disk at offsets 53-95, maxed false complete_len 43
 DEBUG sled::pagecache::iobuf    > mark_interval(53, 43)
 DEBUG sled::pagecache::iobuf    > new highest interval: 53 - 95
LiveReload enabled
created public/bundle.js in 33.6s
bundles native/main.ts → native/main.comp.js...
created native/main.comp.js in 5.5s

[2021-01-09 00:53:35] waiting for changes...
 DEBUG hyper::proto::h1::io      > read 0 bytes 
 DEBUG hyper::proto::h1::conn    > read eof 
(node:255818) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
 DEBUG hyper::proto::h1::io      > read 409 bytes 
 DEBUG hyper::proto::h1::io      > parsed 10 headers 
 DEBUG hyper::proto::h1::conn    > incoming body is empty 
 DEBUG sled::meta                > allocated pid 5 for root of new_tree [115, 101, 115, 115, 105, 111, 110]
 ERROR api::http::error          > Rejection(NoSession)
 INFO  proxy::http               > "GET /v1/session HTTP/1.1" 404 2.422376ms
 DEBUG hyper::proto::h1::io      > flushed 182 bytes 
 DEBUG sled::pagecache::iobuf    > advancing offset within the current segment from 96 to 164
 DEBUG sled::pagecache::iobuf    > wrote lsns 96-163 to disk at offsets 96-163, maxed false complete_len 68
 DEBUG sled::pagecache::iobuf    > mark_interval(96, 68)
 DEBUG sled::pagecache::iobuf    > new highest interval: 96 - 163

(electron:255818): IBUS-WARNING **: 00:53:42.052: Unable to connect to ibus: Could not connect: Connection refused
 DEBUG hyper::proto::h1::io      > read 456 bytes 
 DEBUG hyper::proto::h1::io      > parsed 11 headers 
 DEBUG hyper::proto::h1::conn    > incoming body is content-length (25 bytes) 
 DEBUG hyper::proto::h1::conn    > incoming body completed 
 DEBUG hyper::server::shutdown   > signal received, starting graceful shutdown 
 INFO  proxy::http               > "POST /v1/keystore HTTP/1.1" 204 15.176045874s
 DEBUG hyper::proto::h1::io      > flushed 180 bytes 
 DEBUG sled::pagecache::logger   > IoBufs dropped
 DEBUG api::process              > aborted
 DEBUG sled::pagecache::snapshot > no previous snapshot found
 DEBUG sled::pagecache::iterator > ordering before clearing tears: {0: 0}, max_header_stable_lsn: 0
 DEBUG sled::pagecache::iterator > in clean_tail_tears, found missing item in tail: None and we'll scan segments {0: 0} above lowest lsn 0
 DEBUG sled::pagecache::iterator > filtering out segments after detected tear at (lsn, lid) 163
 DEBUG sled::pagecache::iterator > hit max_lsn 163 in iterator, stopping
 DEBUG sled::pagecache::snapshot > zeroing the end of the recovered segment at lsn 0 between lids 164 and 524287
 DEBUG sled::pagecache::blob_io  > gc_blobs removing any blob with an lsn above 164
 DEBUG sled::pagecache::segment  > SA starting with tip 524288 stable -1 free {}
 DEBUG sled::pagecache::iobuf    > starting log at recovered active offset 164, recovered lsn 164
 DEBUG sled::pagecache::iobuf    > starting IoBufs with next_lsn: 164 next_lid: 164
 DEBUG sled::pagecache           > load_snapshot loading pages from 0..6
 INFO  librad::net::protocol     > Protocol::run; local.id=hydmafd9hr78txg81eyw1mcfnmseb7n4e3zz7nnkwty4nkpj9by6ig local.addr=0.0.0.0:51346
 INFO  api::process              > starting API
 INFO  api::process              > starting peer
 INFO  librad::net::protocol     > Listening 
 DEBUG sled::meta                > allocated pid 7 for root of new_tree [119, 97, 105, 116, 105, 110, 103, 95, 114, 111, 111, 109]
 INFO  librad::net::protocol     > establishing connection remote.id=hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw remote.addr=34.91.29.42:12345 
 DEBUG coco::peer::subroutines   > handling subroutine input: Protocol(Listening(0.0.0.0:51346))
 DEBUG coco::peer::subroutines   > handling subroutine input: Announce(Tick)
 DEBUG rustls::client::hs        > No cached session for DNSNameRef("hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw")
 DEBUG rustls::client::hs        > Not resuming any session
 INFO  quinn::connection         > drive; id=0
 DEBUG coco::peer::subroutines   > handling subroutine input: Request(Tick)
 DEBUG sled::meta                > allocated pid 9 for root of new_tree [97, 110, 110, 111, 117, 110, 99, 101, 109, 101, 110, 116, 115]
 DEBUG coco::peer::subroutines   > handling subroutine input: Announce(Succeeded({}))
 INFO  quinn::connection         > drive; id=0
 DEBUG quinn_proto::connection   > discarding unexpected Data packet (138 bytes) 
 DEBUG quinn_proto::connection   > ECN not acknowledged by peer 
 DEBUG rustls::client::hs        > Using ciphersuite TLS13_CHACHA20_POLY1305_SHA256
 DEBUG rustls::client::tls13     > Not resuming
 DEBUG rustls::client::tls13     > TLS1.3 encrypted extensions: [Protocols([PayloadU8([114, 97, 100, 47, 49])]), ServerNameAck, TransportParameters([1, 4, 128, 0, 253, 232, 3, 4, 128, 0, 255, 228, 4, 4, 128, 152, 150, 128, 5, 4, 128, 19, 18, 208, 6, 4, 128, 19, 18, 208, 7, 4, 128, 19, 18, 208, 8, 1, 32, 9, 1, 32, 11, 1, 0, 14, 1, 5, 64, 182, 0, 2, 16, 7, 182, 92, 60, 253, 235, 104, 84, 3, 60, 156, 177, 161, 136, 127, 241, 32, 4, 128, 0, 255, 255, 0, 20, 215, 49, 112, 7, 28, 158, 0, 8, 159, 31, 251, 212, 247, 179, 131, 254, 203, 119, 21, 75, 15, 8, 214, 80, 167, 148, 168, 182, 57, 99])]
 DEBUG rustls::client::hs        > ALPN protocol is Some([114, 97, 100, 47, 49])
 DEBUG rustls::client::tls13     > Got CertificateRequest CertificateRequestPayloadTLS13 { context: PayloadU8([]), extensions: [SignatureAlgorithms([ECDSA_NISTP384_SHA384, ECDSA_NISTP256_SHA256, ED25519, RSA_PSS_SHA512, RSA_PSS_SHA384, RSA_PSS_SHA256, RSA_PKCS1_SHA512, RSA_PKCS1_SHA384, RSA_PKCS1_SHA256])] }
 DEBUG rustls::client::tls13     > Attempting client auth
 INFO  quinn::connection         > drive; id=0
 INFO  librad::net::protocol     > New outgoing connection remote.id=hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw 
 INFO  tracing::span             > incoming
 DEBUG coco::peer::subroutines   > handling subroutine input: Protocol(Connected(PeerId(PublicKey(VerificationKeyBytes("9146828e4f9fa5bcc9eda09e4d194126c021f5072017bf439fe9ef71fc095c1a")))))
 INFO  quinn::connection         > drive; id=0
 DEBUG coco::peer::sync          > Starting sync from hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw
 DEBUG coco::peer::subroutines   > handling subroutine input: PeerSync(Started(PeerId(PublicKey(VerificationKeyBytes("9146828e4f9fa5bcc9eda09e4d194126c021f5072017bf439fe9ef71fc095c1a")))))
 ERROR coco::peer::subroutines   > sync error for hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw: State(Storage(Config(Unset { config_key: "rad.self" })))
 DEBUG coco::peer::subroutines   > handling subroutine input: PeerSync(Failed(PeerId(PublicKey(VerificationKeyBytes("9146828e4f9fa5bcc9eda09e4d194126c021f5072017bf439fe9ef71fc095c1a")))))
 DEBUG sled::pagecache::iobuf    > advancing offset within the current segment from 164 to 343
 DEBUG sled::pagecache::iobuf    > wrote lsns 164-342 to disk at offsets 164-342, maxed false complete_len 179
 DEBUG sled::pagecache::iobuf    > mark_interval(164, 179)
 DEBUG sled::pagecache::iobuf    > new highest interval: 164 - 342
 INFO  quinn::connection         > drive; id=0
 DEBUG rustls::client::tls13     > Ticket saved
 INFO  quinn::connection         > drive; id=0
 INFO  quinn::connection         > drive; id=0
 INFO  quinn::connection         > drive; id=0
```

Both logs were collected when running `RUST_LOG=debug yarn start`.

I confirm that all the directories (`~/.radicle`, `~/.config/[Rr]adicle*`, `~/.local/share/[Rr]adicle*`) are deleted after erasing the script and there are no alive Radicle-related processes after stopping Radicle with Ctrl+C.

**Comment by FintanH** [comment]
The details in your report are really helpful @imachug :+1: 
```
ERROR coco::peer::subroutines   > sync error for hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw: State(Storage(Config(Unset { config_key: "rad.self" })))
```

This line is likely to be the root cause. In the storage's config, we designate a special URN that points to your user identity. This identity is the one you create at the onboarding screen. It's used in a lot of the operations where there's a need for an owner of some other identity, i.e. projects.

If anyone runs into this again could they also try to share what the contents of `~/.local/share/radicle/git/config` is, as well as any of the steps you took before hitting this error. I'd like to confirm that, for whatever reason, this entry is missing and go from there.

**Comment by aureooms** [comment]
I had the same problem with the `upstream-electron-bin` AUR release the first time I started it. I got it to work after running the following (I do not know if it may remove important files):

```
rm -rf .radicle .config/radicle/ .config/Radicle\ Upstream/ .local/share/radicle .local/share/radicle-upstream/
```

**Comment by zesicus** [comment]
Mine is macOS and I global search `radicle` and delete those folders and files, now I'm able to create identity.
