### ISSUE TITLE
Thread panic 

### ISSUE THREAD

**Issue by xni** [radicle-dev/radicle-upstream#1625]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: 
.. }"', /root/.cargo/git/checkouts/quinn-572d2e5812b43165/babb07b/quinn/src/endpoint.rs:215:42

```
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    0:     0x5586f0f28ee0 - std::backtrace_rs::backtrace::libunwind::trace::h448c56741b6011d3
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/../../backtr
ace/src/backtrace/libunwind.rs:100:5
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    1:     0x5586f0f28ee0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2d26397c5720fdbb
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/../../backtr
ace/src/backtrace/mod.rs:66:5
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    2:     0x5586f0f28ee0 - std::sys_common::backtrace::_print_fmt::h720a2f61f75b9f58
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/b
acktrace.rs:67:5
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    3:     0x5586f0f28ee0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::
h8d62bbfda6d5c836
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/b
acktrace.rs:46:22
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    4:     0x5586f0f4d3bc - core::fmt::write::h1857a60b204f1b6a
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/core/src/fmt/mod.rs:
1078:17
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    5:     0x5586f0f21d22 - std::io::Write::write_fmt::h16a9fe7680ac245c
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/io/mod.rs:15
18:15
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    6:     0x5586f0f2b625 - std::sys_common::backtrace::_print::h9ba51a6db618de7d
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/b
acktrace.rs:49:5
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    7:     0x5586f0f2b625 - std::sys_common::backtrace::print::h5f20e41c85e91716
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/b
acktrace.rs:36:9
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    8:     0x5586f0f2b625 - std::panicking::default_hook::{{closure}}::h5b7294ca19e8edab
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs
:208:50
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:    9:     0x5586f0f2b2c8 - std::panicking::default_hook::hb3948d1f74b6ff4c
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs
:227:9
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   10:     0x5586f0f2bdc1 - std::panicking::rust_panic_with_hook::h55d23fef0ad751bc
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs
:593:17
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   11:     0x5586f0f2b907 - std::panicking::begin_panic_handler::{{closure}}::h56ae74c6dea6e141
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs
:499:13
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   12:     0x5586f0f2937c - std::sys_common::backtrace::__rust_end_short_backtrace::h3c4721f56689fae4
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/backtrace.rs:141:18
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   13:     0x5586f0f2b869 - rust_begin_unwind
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs:495:5
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   14:     0x5586f0f4ba41 - core::panicking::panic_fmt::hb15d6f55e8472f62
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/core/src/panicking.rs:92:14
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   15:     0x5586f0f4b863 - core::option::expect_none_failed::he492a18657d97593
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/core/src/option.rs:1268:5
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   16:     0x5586f09532f7 - <quinn::endpoint::EndpointDriver<S> as core::ops::drop::Drop>::drop::hf6609bd4b85ab246
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   17:     0x5586f09b8bfc - core::ptr::drop_in_place::hc5d5b5564867ff02
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   18:     0x5586f09ecbc4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb84101ac49335b80
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   19:     0x5586f098689f - tokio::runtime::task::core::Core<T,S>::poll::h4b4cdf6c18b0e0af
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   20:     0x5586f0a28063 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h73ea7e298eafc365
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   21:     0x5586f08ea4d9 - tokio::runtime::task::harness::Harness<T,S>::poll::h1afdddf231f629a2
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   22:     0x5586f0d6f384 - std::thread::local::LocalKey<T>::with::h9444a050fb35ddab
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   23:     0x5586f0d91c72 - tokio::runtime::thread_pool::worker::Context::run_task::h39c973c7a2016f80
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   24:     0x5586f0d91420 - tokio::runtime::thread_pool::worker::Context::run::h762cdead5d5aad8c
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   25:     0x5586f0d71145 - tokio::macros::scoped_tls::ScopedKey<T>::set::hd875dbb86d2a131c
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   26:     0x5586f0d90ef6 - tokio::runtime::thread_pool::worker::run::h1417bd1fc40d0fcc
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   27:     0x5586f0d8a050 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::he98d637d25b2387c
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   28:     0x5586f0d8d548 - tokio::runtime::task::core::Core<T,S>::poll::h107da107dc6ef3be
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   29:     0x5586f0d981b3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9091a29b5eef434b
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   30:     0x5586f0d74b03 - tokio::runtime::task::harness::Harness<T,S>::poll::h2cbe9d612103df60
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   31:     0x5586f0d73491 - tokio::runtime::blocking::pool::Inner::run::hd8ec43e27f0dc16b
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   32:     0x5586f0d82ff8 - tokio::runtime::context::enter::heeaeebbf6b2fe24d
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   33:     0x5586f0d6f15f - std::sys_common::backtrace::__rust_begin_short_backtrace::h345ab8543e43f4d8
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   34:     0x5586f0d81a10 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8c63fce45e0be2a2
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   35:     0x5586f0f32bea - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9e7afb7a0a438236
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/alloc/src/boxed.rs:1307:9
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   36:     0x5586f0f32bea - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70c646c4271337a1
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/alloc/src/boxed.rs:1307:9
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   37:     0x5586f0f32bea - std::sys::unix::thread::Thread::new::thread_start::h35d2b8d36f210d02
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:                                at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys/unix/thread.rs:89:17
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   38:     0x7fcae55ef6db - start_thread
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   39:     0x7fcae4d7671f - __clone
Feb 21 03:07:54 Ubuntu-1804-bionic-64-minimal radicle-run.sh[3885]:   40:                0x0 - <unknown>
```

**Comment by xni** [comment]
moved to https://github.com/radicle-dev/radicle-bins/issues/66
