### ISSUE TITLE
Cannot generate new identity in upstream client

### ISSUE THREAD

**Issue by trader-payne** [radicle-dev/radicle-upstream#2011]
Running Big Sur 11.4 on a MacBook Air 13" M1 chip

### Steps for how I got into this state:

- went here: https://radicle.xyz/downloads.html
- downloaded the MacOS client
- installed it
- filled my name
- filled passphrase

Errors I've seen thus far:

### First run:
```
{
  "stack": "Error: Could not create identity\n    at file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2446883\n    at Generator.throw (<anonymous>)\n    at f (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2446244)",
  "message": "Could not create identity",
  "code": "IdentityCreationFailure",
  "details": {
    "handle": "payne"
  },
  "source": {
    "stack": "TypeError: Failed to fetch",
    "message": "Failed to fetch",
    "code": "UnknownException",
    "details": {
      "name": "TypeError"
    }
  }
}
```
Then after trying again:
```
{
  "stack": "Error: Could not create identity\n    at file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2446883\n    at Generator.throw (<anonymous>)\n    at f (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2446244)",
  "message": "Could not create identity",
  "code": "IdentityCreationFailure",
  "details": {
    "handle": "payne"
  },
  "source": {
    "stack": "Error: incorrect passphrase\n    at Dt.fetchOkNoContent (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:1866833)",
    "message": "incorrect passphrase",
    "code": "UnknownException",
    "details": {
      "name": "Error",
      "body": {
        "message": "incorrect passphrase",
        "variant": "INCORRECT_PASSPHRASE"
      },
      "response": {}
    }
  }
}
```

### Cleared the state with the script, then gave it another shot:
```
{
  "stack": "Error: Could not create identity\n    at file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2446883\n    at Generator.throw (<anonymous>)\n    at f (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2446244)",
  "message": "Could not create identity",
  "code": "IdentityCreationFailure",
  "details": {
    "handle": "payne"
  },
  "source": {
    "stack": "TypeError: Failed to fetch",
    "message": "Failed to fetch",
    "code": "UnknownException",
    "details": {
      "name": "TypeError"
    }
  }
}
```
Then after trying again:
```
{
  "stack": "Error: Could not create identity\n    at file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2446883\n    at Generator.throw (<anonymous>)\n    at f (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2446244)",
  "message": "Could not create identity",
  "code": "IdentityCreationFailure",
  "details": {
    "handle": "payne"
  },
  "source": {
    "stack": "Error: A key already exists\n    at Dt.fetchOkNoContent (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:1866833)",
    "message": "A key already exists",
    "code": "UnknownException",
    "details": {
      "name": "Error",
      "body": {
        "message": "A key already exists",
        "variant": "KEY_EXISTS"
      },
      "response": {}
    }
  }
}
```

**Comment by rudolfs** [comment]
This might be relevant: "the passphrase I'm generating with a password manager and copy pasting it into the client".

<img width="418" alt="Screenshot 2021-06-17 at 11 10 28" src="https://user-images.githubusercontent.com/158411/122367395-afe6a000-cf5c-11eb-9536-0bddcc8ced9d.png">

Might be something with special characters or password length.

**Comment by trader-payne** [comment]
I also tried 16 lowercase letters and it didn't work 🤷🏻

**Comment by rudolfs** [comment]
Just to confirm, to reset the app state you used [this script](https://github.com/radicle-dev/radicle-upstream/blob/master/scripts/reset-state.sh)?

**Comment by trader-payne** [comment]
Yes, correct 👍🏻

**Comment by rudolfs** [comment]
And I assume the app version is `0.2.6`?

**Comment by trader-payne** [comment]
I nuked it again with the script and manually set a short alphanumeric passphrase and this time it worked out. 🤔

**Comment by geigerzaehler** [comment]
@trader-payne Would you mind sharing one of the passwords that didn’t work so we can try to reproduce this? If you start the app from the command line you will also be able to see more logs. It would be great if you could share these logs when setting up a new profile fails.

**Comment by trader-payne** [comment]
I dont't have the passwords anymore, not even in history (the pwd manager resets automatically after some time) but they were looking like this, for when I tried with 128 char: 
```
6Xrhay6ibhsNtH8n&9Bt7wgH94jN1^LvP3x$&^ytp*@bvH@NU*4lDKkW3JbTG%143x3*JC4!w*H@Dv*IsZS2M#0UVQlLj1ul*%^u4IT2SF0D9!g2#p^InPQ3yL*iWq^*
```
I can try to reproduce again

**Comment by trader-payne** [comment]
Alright I reinstalled the client, then tried again with a pwd manager generated password and it worked without any errors. 🤷🏻

**Comment by geigerzaehler** [comment]
Thanks for trying this again @trader-payne. To bad we weren’t able to reproduce this. I’ll close this for now. If somebody runs in to this issue again we will reopen.
