### ISSUE TITLE
Orgs error despite doing nothing related to orgs

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2042]
Here's the error I got:

```
{
  "stack": "Error: Failed to fetch org data\n    at eval (webpack-internal:///./ui/src/org.ts:107:64)\n    at async updateOrgsForever (webpack-internal:///./ui/src/org.ts:99:9)",
  "message": "Failed to fetch org data",
  "code": "OrgFetchFailed",
  "source": {
    "stack": "Error: Unexpected token < in JSON at position 0\n    at new ApolloError (webpack-internal:///./node_modules/@apollo/client/errors/index.js:33:28)\n    at eval (webpack-internal:///./node_modules/@apollo/client/core/QueryManager.js:559:19)\n    at both (webpack-internal:///./node_modules/@apollo/client/utilities/observables/asyncMap.js:22:53)\n    at eval (webpack-internal:///./node_modules/@apollo/client/utilities/observables/asyncMap.js:15:72)\n    at new Promise (<anonymous>)\n    at Object.then (webpack-internal:///./node_modules/@apollo/client/utilities/observables/asyncMap.js:15:24)\n    at Object.eval [as error] (webpack-internal:///./node_modules/@apollo/client/utilities/observables/asyncMap.js:23:49)\n    at notifySubscription (webpack-internal:///./node_modules/zen-observable/lib/Observable.js:140:18)\n    at onNotify (webpack-internal:///./node_modules/zen-observable/lib/Observable.js:179:3)\n    at SubscriptionObserver.error (webpack-internal:///./node_modules/zen-observable/lib/Observable.js:240:7)",
    "message": "Unexpected token < in JSON at position 0",
    "code": "UnknownException",
    "details": {
      "name": "Error",
      "graphQLErrors": [],
      "networkError": {
        "name": "ServerParseError",
        "response": {},
        "statusCode": 502,
        "bodyText": "<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n<meta http-equiv=\"refresh\" content=\"0\">\n\n<title>api.thegraph.com | 502: Bad gateway</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" type=\"text/css\" media=\"screen,projection\" />\n\n\n</head>\n<body>\n<div id=\"cf-wrapper\">\n\n    \n\n    <div id=\"cf-error-details\" class=\"p-0\">\n        <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8\">\n            <h1 class=\"inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2\">\n              \n              <span class=\"cf-error-type\">Error</span>\n              <span class=\"cf-error-code\">502</span>\n            </h1>\n            <span class=\"inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed\">Ray ID: 662d08ada26f05b3 &bull;</span>\n            <span class=\"inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed\">2021-06-21 11:52:59 UTC</span>\n            <h2 class=\"text-gray-600 leading-1.3 text-3xl font-light\">Bad gateway</h2>\n        </header>\n        \n        <div class=\"my-8 bg-gradient-gray\">\n            <div class=\"w-240 lg:w-full mx-auto\">\n                <div class=\"clearfix md:px-8\">\n                  \n<div id=\"cf-browser-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    <span class=\"cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n  </div>\n  <span class=\"md:block w-full truncate\">You</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">Browser</h3>\n  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n</div>\n\n<div id=\"cf-cloudflare-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    <span class=\"cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n  </div>\n  <span class=\"md:block w-full truncate\">Frankfurt</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">Cloudflare</h3>\n  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n</div>\n\n<div id=\"cf-host-status\" class=\"cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    <span class=\"cf-icon-server block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n  </div>\n  <span class=\"md:block w-full truncate\">api.thegraph.com</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">Host</h3>\n  <span class=\"leading-1.3 text-2xl text-red-error\">Error</span>\n</div>\n\n                </div>\n              \n            </div>\n        </div>\n\n        <div class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n            <div class=\"clearfix\">\n                <div class=\"w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed\">\n                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What happened?</h2>\n                    <p>The web server reported a bad gateway error.</p>\n                </div>\n              \n                <div class=\"w-1/2 md:w-full float-left leading-relaxed\">\n                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What can I do?</h2>\n                    <p class=\"mb-6\">Please try again in a few minutes.</p>\n                </div>\n            </div>\n              \n        </div>\n\n        <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n  <p class=\"text-13\">\n    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">662d08ada26f05b3</strong></span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Your IP</span>: 95.91.210.14</span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n</div><!-- /.error-footer -->\n\n\n    </div>\n</div>\n<script defer src=\"https://static.cloudflareinsights.com/beacon.min.js\" data-cf-beacon='{\"rayId\":\"662d08ad991705b3\",\"token\":\"8aff362e136740cd82eeeb1ea39b8b0e\",\"version\":\"2021.5.2\",\"si\":10}'></script>\n</body>\n</html>\n\n"
      }
    }
  }
}
```

**Comment by rudolfs** [comment]
We're polling the org list for the sidebar every 2 seconds. If there's a networking error, we show it once. Should we not inform the user in this case?

**Comment by brandonhaslegs** [comment]
Well I had not created any orgs and also wasn't trying to create an org, so the notification was just random. In this case where the user has no orgs, we should not inform the user of an error about orgs.

**Comment by rudolfs** [comment]
But the only way for the app to know whether the user is part of any orgs it has to check. And this error happened during that check.

We do it periodically every 2 seconds in case somebody else adds you to an org, so that it gets immediately reflected in your sidebar.

**Comment by geigerzaehler** [comment]
To clarify: This error only happens if the user is connected with a wallet. In this particular case I think it would make sense to retry since it was a 502 error. I’ll add this to the list of org issues.
