### ISSUE TITLE
pass gas estimation to wallet via radicle-upstream

### ISSUE THREAD

**Issue by pimato** [radicle-dev/radicle-upstream#2154]
It looks like upstream is not correctly telling the gnosis-safe wallet which gas price it should use for a transaction. This could lead to users sending transactions out which might never get confirmed.
<img width="534" alt="Bildschirmfoto 2021-07-20 um 20 55 55" src="https://user-images.githubusercontent.com/5337809/126380074-dc28cf34-d815-446d-bb48-ddc08895db4e.png">

**Comment by pimato** [comment]
Also after signing the transaction I got this:
<img width="2869" alt="Bildschirmfoto 2021-07-20 um 20 58 18" src="https://user-images.githubusercontent.com/5337809/126380275-7a682c9b-b7cc-4ca0-8c18-28a58b258a9d.png">

```
{
  "stack": "Error: failed response (requestBody=\"{\\\"method\\\":\\\"eth_getLogs\\\",\\\"params\\\":[{\\\"fromBlock\\\":\\\"0x0\\\",\\\"toBlock\\\":\\\"latest\\\",\\\"address\\\":\\\"0x4a7dfda4f2e9f062965cc87f775841fb58aea83e\\\",\\\"topics\\\":[\\\"0xb449c24d261a59627b537c8c41c57ab559f4205c56bea745ff61c5521bece214\\\",\\\"0x000000000000000000000000441428454b614d2bb2782165ef1cee53da79dd93\\\"]}],\\\"id\\\":55,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://mainnet.infura.io/v3/7a19a4bf0af84fcc86ffb693a257fad4\", code=SERVER_ERROR, version=web/5.3.0)\n    at l.makeError (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:82965)\n    at l.throwError (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:83085)\n    at file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:194625\n    at Generator.next (<anonymous>)\n    at a (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:190986)",
  "message": "failed response (requestBody=\"{\\\"method\\\":\\\"eth_getLogs\\\",\\\"params\\\":[{\\\"fromBlock\\\":\\\"0x0\\\",\\\"toBlock\\\":\\\"latest\\\",\\\"address\\\":\\\"0x4a7dfda4f2e9f062965cc87f775841fb58aea83e\\\",\\\"topics\\\":[\\\"0xb449c24d261a59627b537c8c41c57ab559f4205c56bea745ff61c5521bece214\\\",\\\"0x000000000000000000000000441428454b614d2bb2782165ef1cee53da79dd93\\\"]}],\\\"id\\\":55,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://mainnet.infura.io/v3/7a19a4bf0af84fcc86ffb693a257fad4\", code=SERVER_ERROR, version=web/5.3.0)",
  "code": "UnhandledRejection",
  "details": {
    "name": "Error",
    "reason": "failed response",
    "code": "SERVER_ERROR",
    "requestBody": "{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x0\",\"toBlock\":\"latest\",\"address\":\"0x4a7dfda4f2e9f062965cc87f775841fb58aea83e\",\"topics\":[\"0xb449c24d261a59627b537c8c41c57ab559f4205c56bea745ff61c5521bece214\",\"0x000000000000000000000000441428454b614d2bb2782165ef1cee53da79dd93\"]}],\"id\":55,\"jsonrpc\":\"2.0\"}",
    "requestMethod": "POST",
    "url": "https://mainnet.infura.io/v3/7a19a4bf0af84fcc86ffb693a257fad4"
  }
}```

**Comment by geigerzaehler** [comment]
Thanks for reporting this @pimato . As far as I know the gas price for the owner transaction is determined by the wallet that is connected with the Gnosis safe or the safe app itself and should be automatically adjusted. Upstream only sets the “safe transaction” properties and these look alright. So this is either an issue with the wallet your using or Gnosis safe.
