### ISSUE TITLE
"Failed to fetch org data"

### ISSUE THREAD

**Issue by RMBLRX** [radicle-dev/radicle-upstream#2183]
When I open either of the last two versions of Radicle on Linux, I get a warning that I'm unable to fetch org data, and my org does not show up on the sidebar.

```
{
  "stack": "Error: Failed to fetch org data\n    at file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:17:12688\n    at async file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:17:12595",
  "message": "Failed to fetch org data",
  "code": "OrgFetchFailed",
  "source": {
    "stack": "Error: Unexpected token < in JSON at position 0\n    at new t (file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:1:2416006)\n    at file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:1:2451573\n    at n (file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:1:2415573)\n    at file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:1:2415498\n    at new Promise (<anonymous>)\n    at Object.then (file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:1:2415464)\n    at Object.error (file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:1:2415583)\n    at g (file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:1:1851421)\n    at v (file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:1:1851878)\n    at e.value (file:///tmp/.mount_radiclMBLh1M/resources/app.asar/public/bundle.js:1:1852495)",
    "message": "Unexpected token < in JSON at position 0",
    "code": "UnknownException",
    "details": {
      "name": "Error",
      "graphQLErrors": [],
      "networkError": {
        "name": "ServerParseError",
        "response": {},
        "statusCode": 503,
        "bodyText": "<html>\n<head><title>503 Service Temporarily Unavailable</title><script src=\"/cdn-cgi/apps/head/a-7iaLT0SRdb_kvxGKIYLrjkGzU.js\"></script></head>\n<body>\n<center><h1>503 Service Temporarily Unavailable</h1></center>\n<hr><center>nginx</center>\n<script defer src=\"https://static.cloudflareinsights.com/beacon.min.js\" data-cf-beacon='{\"rayId\":\"67504b93af6bc7cd\",\"token\":\"8aff362e136740cd82eeeb1ea39b8b0e\",\"version\":\"2021.7.0\",\"si\":10}'></script>\n</body>\n</html>\n\n\n\n\n\n\n"
      }
    }
  }
}
```

**Comment by RMBLRX** [comment]
A fresh install apparently fixed the issue.

**Comment by geigerzaehler** [comment]
Thanks for the report @RMBLRX. The error was caused by the API for The Graph not being available intermittently. However, this should not result in us displaying an error to the user but instead retrying the request. We’re fixing this in #2186.
