### ISSUE TITLE
Can't relogin to my Radicle account

### ISSUE THREAD

**Issue by talentlessguy** [radicle-dev/radicle-upstream#2187]
After erasing the local data because of #2181 I used the same password and synced my wallet. Then I pushed one of my repos to `rad` origin.

Now when I try to open a repo I see this error:

```
{
  "stack": "Error: we could not find the 'refs/namespaces/hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny/refs/heads/master'\n    at zg (file:///tmp/.mount_radiclMVd456/resources/app.asar/public/bundle.js:1:2257314)\n    at async Promise.all (index 0)\n    at async file:///tmp/.mount_radiclMVd456/resources/app.asar/public/bundle.js:35:340942",
  "message": "we could not find the 'refs/namespaces/hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny/refs/heads/master'",
  "code": "UnknownException",
  "details": {
    "name": "Error",
    "response": {}
  }
}
```

Also idk why but for some reason I now have two remote IDs? How can I return back to my previous remote?

![image](https://user-images.githubusercontent.com/35937217/127307232-64bd38a5-2b17-46e1-b55b-2a345f9c5c5b.png)

this is what I get in logs:

```
Jul 28 13:24:39.981 ERROR api::http::error: request error err=Rejection(State(MissingRef { reference: Reference { remote: None, category: Heads, name: RefLike("master"), namespace: Some(Namespace(Urn { id: Oid(2275af999c833563bf79a51fa27cda5dea260944), path: None })) } }))
Jul 28 13:24:39.981  INFO proxy::http: GET /v1/source/branches/rad:git:hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny 500 elapsed=607.932µs
Jul 28 13:24:40.014  INFO proxy::http: GET /v1/source/tags/rad:git:hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny 200 elapsed=32.824211ms
Jul 28 13:24:41.775  INFO proxy::http: GET /v1/projects/contributed 200 elapsed=46.824227ms
Jul 28 13:24:41.776  INFO proxy::http: GET /v1/projects/failed 200 elapsed=46.838385ms
Jul 28 13:24:42.746  INFO proxy::http: GET /v1/projects/tracked 200 elapsed=52.499523ms
Jul 28 13:24:42.746  INFO proxy::http: GET /v1/projects/contributed 200 elapsed=51.491961ms
Jul 28 13:24:43.034  INFO proxy::http: GET /v1/projects/rad:git:hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny 200 elapsed=47.671384ms
Jul 28 13:24:44.379  INFO proxy::http: GET /v1/projects/rad:git:hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny 200 elapsed=43.573667ms
Jul 28 13:24:44.383  INFO proxy::http: GET /v1/projects/rad:git:hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny/peers 200 elapsed=1.844409ms
Jul 28 13:24:44.391 ERROR api::http::error: request error err=Rejection(State(MissingRef { reference: Reference { remote: None, category: Heads, name: RefLike("master"), namespace: Some(Namespace(Urn { id: Oid(2275af999c833563bf79a51fa27cda5dea260944), path: None })) } }))
Jul 28 13:24:44.391  INFO proxy::http: GET /v1/source/branches/rad:git:hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny 500 elapsed=577.176µs
Jul 28 13:24:44.418  INFO proxy::http: GET /v1/source/tags/rad:git:hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny 200 elapsed=27.160262ms
```

**Comment by geigerzaehler** [comment]
This looks like an issue with the protocol. Could you take a look at this @FintanH or @xla?

> Also idk why but for some reason I now have two remote IDs? How can I return back to my previous remote?

As explained on discord, there are two remotes with your name because you created a new identity. Since you deleted the data for the old identity there’s no way to get it back unfortunately.

**Comment by FintanH** [comment]
@talentlessguy, if you could get the following info for me that would help me suss out what's going on.

Could you `tree` your `~/.local/share/radicle-link/<some uuid>/git/refs` and also `more .git/config` in the project's working copy.

Thanks!

**Comment by talentlessguy** [comment]
@geigerzaehler got it... then rest in peace my old identity....

**Comment by talentlessguy** [comment]
@FintanH 

```
tinyhttp on  esm via ⬢ v14.17.3 
➜ ls --tree ~/.local/share/radicle-link/52df46a5-be2a-463d-b8fe-ffda8d636a64/git/refs
 refs
├──  heads
├──  namespaces
│  ├──  hnrkb9iwxg8cyr9ekzfypeyadpdtzkyoii5to
│  │  └──  refs
│  │     └──  rad
│  │        ├──  id
│  │        ├──  self
│  │        └──  signed_refs
│  ├──  hnrkg3kaea8prkjhyjnbbsrhqtw97w1y4qoro
│  │  └──  refs
│  │     ├──  heads
│  │     │  ├──  esm
│  │     │  └──  master
│  │     └──  rad
│  │        ├──  id
│  │        ├──  ids
│  │        │  └──  hnrkb9iwxg8cyr9ekzfypeyadpdtzkyoii5to
│  │        ├──  self
│  │        └──  signed_refs
│  ├──  hnrkmoqezqw6gekong7i4r4o68e3znuo8n7qy
│  │  └──  refs
│  │     └──  rad
│  │        └──  id
│  └──  hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny
│     └──  refs
│        ├──  heads
│        │  └──  esm
│        ├──  rad
│        │  ├──  id
│        │  ├──  ids
│        │  │  └──  hnrkmoqezqw6gekong7i4r4o68e3znuo8n7qy
│        │  ├──  self
│        │  └──  signed_refs
│        └──  remotes
│           ├──  hydntk87mtiqrw11qdxc6f7wx4c4txpdwec19ici8zptjqy9s9wzfy
│           │  ├──  heads
│           │  │  ├──  esm
│           │  │  └──  master
│           │  └──  rad
│           │     ├──  id
│           │     ├──  ids
│           │     │  └──  hnrkmoqezqw6gekong7i4r4o68e3znuo8n7qy
│           │     ├──  self
│           │     └──  signed_refs
│           └──  hynkyndc6w3p8urucakobzna7sxwgcqny7xxtw88dtx3pkf7m3nrzc
│              └──  rad
│                 ├──  id
│                 ├──  ids
│                 │  └──  hnrkmoqezqw6gekong7i4r4o68e3znuo8n7qy
│                 └──  signed_refs
└──  tags

tinyhttp on  esm via ⬢ v14.17.3 
➜ more .git/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        hooksPath = .husky
[remote "origin"]
        url = https://github.com/tinyhttp/tinyhttp.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[include]
        path = /home/v1rtl/.config/radicle-link/52df46a5-be2a-463d-b8fe-ffda8d636a64/git-includes/hnrkg3kaea8prkjhyjnbbsrhqtw97w1y4qoro.inc
[branch "esm"]
        remote = origin
        merge = refs/heads/esm
[remote "rad"]
        url = rad://hnrkg3kaea8prkjhyjnbbsrhqtw97w1y4qoro.git
        fetch = +refs/heads/*:refs/remotes/rad/*

```

**Comment by FintanH** [comment]
The `.git/config` you linked doesn't match up with ID the error is about, i.e. `hnrknr7pxugqegpmdz7h4k87nxupf54tgbfny`. That project doesn't have a `master` branch underneath it in the output of `ls --tree ~/.local/share/radicle-link/52df46a5-be2a-463d-b8fe-ffda8d636a64/git/refs`. Could you shed some light on how you created that project?

**Comment by talentlessguy** [comment]
@FintanH well, I created the project with one identity, then because of failing session issues I created a new one and pushed to `rad` origin, the push succeeded.

but it wasn't showing in list of my projects but instead was in "following" (even though I could push lol)

then in attempt to create the project again I opened it from local and now on my new remote I have this error

**Comment by FintanH** [comment]
Hmmm sounds like there might be a subtle bug. You didn't have to remove the old `rad` remote or anything?

**Comment by talentlessguy** [comment]
@FintanH ooh oops sorry forgot to mention I think before opening from local i did `git remote remove rad`
