### ISSUE TITLE
"waiting room error" spam in logs after cloning a project

### ISSUE THREAD

**Issue by viraptor** [radicle-dev/radicle-upstream#2327]
After successfully following a project, upstream doesn't display it, but instead I get a spam of:
```
Sep 06 19:32:52.372  WARN radicle_daemon::peer::run_state::running_waiting_room: waiting room error error=MissingUrn(Urn { id: Oid(8cc143b5b061d9882726564702017b5f94bb0f1a), path: Some(RefLike("rad/id")) })
```
many times a second.

UI error popup allows me to copy this:
```
{
  "stack": "Error: The project radicle-docs couldn’t be loaded\n    at file:///tmp/.mount_radiclEw14BK/resources/app.asar/public/bundle.js:35:205692\n    at Array.forEach (<anonymous>)\n    at file:///tmp/.mount_radiclEw14BK/resources/app.asar/public/bundle.js:35:205676",
  "message": "The project radicle-docs couldn’t be loaded",
  "code": "ProjectRequestFailure",
  "details": {
    "urn": "rad:git:hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o",
    "metadata": {
      "name": "radicle-docs",
      "defaultBranch": "master",
      "description": "The Radicle documentation website docs.radicle.xyz",
      "maintainers": [
        "rad:git:hnrkbo46og4rgnprbi46b189hfotwamrs8quo"
      ]
    }
  }
}
```

When switching to the followed projects page, I get:
```
Sep 06 19:35:24.534  WARN api::project: cannot find default branch project_urn=rad:git:hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o err=NoDefaultBranch { name: "radicle-docs", urn: Urn { id: Oid(1cfca4f17494efe22d5dd8947fc5c5520e7d0eff), path: None } }
```

**Comment by geigerzaehler** [comment]
Thanks for reporting this. The waiting room error is unrelated to the other errors. The Oid mentioned in the error corresponds to the URN `rad:git:8cc143b5b061d9882726564702017b5f94bb0f1a`.

To get more information about the other error could you run the following command (if you’re on Linux and don’t use a custom `RAD_HOME`)?

```bash
git --git-dir ~/.local/share/radicle-link/$(cat ~/.config/radicle-link/active_profile)/git show-ref | grep hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o
```

**Comment by viraptor** [comment]
@geigerzaehler here's the list:
```
d57b68e368d73a072098ec51a59a019ea83fe2df refs/namespaces/hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o/refs/rad/id
5e93e06ca57516018f046c3eb7eaccbc9b5c5971 refs/namespaces/hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o/refs/rad/ids/hnrkbo46og4rgnprbi46b189hfotwamrs8quo
dcd6f52bd4efe49ead82a5df6181ba14ff6b0a02 refs/namespaces/hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o/refs/rad/self
5da356336888e34a5000f6abcda046296c90b5a3 refs/namespaces/hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o/refs/rad/signed_refs
d57b68e368d73a072098ec51a59a019ea83fe2df refs/namespaces/hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o/refs/remotes/hydqsnkr181w1zfidtocgosxghdu8n8d1wsemzgtszhzjru55ggazk/rad/id
5e93e06ca57516018f046c3eb7eaccbc9b5c5971 refs/namespaces/hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o/refs/remotes/hydqsnkr181w1zfidtocgosxghdu8n8d1wsemzgtszhzjru55ggazk/rad/ids/hnrkbo46og4rgnprbi46b189hfotwamrs8quo
5e93e06ca57516018f046c3eb7eaccbc9b5c5971 refs/namespaces/hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o/refs/remotes/hydqsnkr181w1zfidtocgosxghdu8n8d1wsemzgtszhzjru55ggazk/rad/self
ccc3be803e17c2487d86b949ce7f0603a6942313 refs/namespaces/hnrkb39fr6f4jj59nfiq7tfd9aznirdu7b59o/refs/remotes/hydqsnkr181w1zfidtocgosxghdu8n8d1wsemzgtszhzjru55ggazk/rad/signed_refs
```

**Comment by geigerzaehler** [comment]
This looks like the same problem that was reported in https://github.com/radicle-dev/radicle-link/issues/782. Since it is a problem with Radicle Link I’ll close this issue. Thanks for reporting anyways.
