### ISSUE TITLE
Could not create identity (on AppImage shared between devices)

### ISSUE THREAD

**Issue by almereyda** [radicle-dev/radicle-upstream#2342]
When running Radicle Upstream from the AppImage on Linux, it is not possible to use a shared "binary" between both machines. Similar to the reports in #1496 it is not possible to create a new identity on the second device.

![Bildschirmfoto von 2021-09-07 16-52-14](https://user-images.githubusercontent.com/1645308/132366342-e68c76f9-f90a-4048-b732-190b5c07f291.png)

```
{
  "stack": "Error: Could not create identity\n    at file:///tmp/.mount_radiclrBspdM/resources/app.asar/public/bundle.js:35:164572\n    at Generator.throw (<anonymous>)\n    at s (file:///tmp/.mount_radiclrBspdM/resources/app.asar/public/bundle.js:35:163902)",
  "message": "Could not create identity",
  "code": "IdentityCreationFailure",
  "details": {
    "handle": "yala"
  },
  "source": {
    "stack": "Error: A key already exists\n    at st.fetchOkNoContent (file:///tmp/.mount_radiclrBspdM/resources/app.asar/public/bundle.js:1:1622545)",
    "message": "A key already exists",
    "code": "UnknownException",
    "details": {
      "name": "Error",
      "variant": "KEY_EXISTS",
      "body": {
        "message": "A key already exists",
        "variant": "KEY_EXISTS"
      },
      "response": {}
    }
  }
}
```

with the AppImage mounted into that directory:

```shell
$ mount | grep radicle
radicle-upstream-0.2.10_68837090c20dccd54c501dcef817ec70.AppImage on /tmp/.mount_radiclrBspdM type fuse.radicle-upstream-0.2.10_68837090c20dccd54c501dcef817ec70.AppImage (ro,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```

Therefore an AppImage is not an immutable asset to be distributed freely between machines, but instead a mutable container which will also contain user specific data? That is surprising.

How would one create a new identity on another machine, sharing an up-to-date binary between each?

**Comment by almereyda** [comment]
It appears the application state will still be used from `.config/radicle-link/`, why deleting the (unique) device keys I had rsync'ed there helped continuing here.
