### ISSUE TITLE
Can't load org while safe update transaction is in progress

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2446]
We get this error when navigating to an org whose gnosis safe has a pending transaction updating its owners.

```
{
  "stack": "Error: no matching function (argument=\"sighash\", value=\"0x0d582f13\", code=INVALID_ARGUMENT, version=abi/5.4.1)\n    at d.makeError (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:99469)\n    at d.throwError (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:99589)\n    at d.throwArgumentError (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:99644)\n    at _.getFunction (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:25159)\n    at _.parseTransaction (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:31555)\n    at file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:23:1517\n    at file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:23:1622\n    at Array.map (<anonymous>)\n    at jM (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:23:1448)\n    at async UM (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:23:1948)",
  "message": "no matching function (argument=\"sighash\", value=\"0x0d582f13\", code=INVALID_ARGUMENT, version=abi/5.4.1)",
  "code": "UnhandledRejection",
  "details": {
    "name": "Error",
    "reason": "no matching function",
    "code": "INVALID_ARGUMENT",
    "argument": "sighash",
    "value": "0x0d582f13"
  }
}
```

**Comment by auryn-macmillan** [comment]
I've just run into this same issue for a radicle org owned by a safe.

```json
{
  "stack": "Error: no matching function (argument=\"sighash\", value=\"0xac9650d8\", code=INVALID_ARGUMENT, version=abi/5.5.0)\n    at d.makeError (file:///tmp/.mount_radiclX9lUxI/resources/app.asar/public/bundle.js:1:92777)\n    at d.throwError (file:///tmp/.mount_radiclX9lUxI/resources/app.asar/public/bundle.js:1:92897)\n    at d.throwArgumentError (file:///tmp/.mount_radiclX9lUxI/resources/app.asar/public/bundle.js:1:92952)\n    at _.getFunction (file:///tmp/.mount_radiclX9lUxI/resources/app.asar/public/bundle.js:1:25159)\n    at _.parseTransaction (file:///tmp/.mount_radiclX9lUxI/resources/app.asar/public/bundle.js:1:31555)\n    at file:///tmp/.mount_radiclX9lUxI/resources/app.asar/public/bundle.js:26:175556\n    at file:///tmp/.mount_radiclX9lUxI/resources/app.asar/public/bundle.js:26:175661\n    at Array.map (<anonymous>)\n    at L$ (file:///tmp/.mount_radiclX9lUxI/resources/app.asar/public/bundle.js:26:175487)\n    at async D$ (file:///tmp/.mount_radiclX9lUxI/resources/app.asar/public/bundle.js:26:175996)",
  "message": "no matching function (argument=\"sighash\", value=\"0xac9650d8\", code=INVALID_ARGUMENT, version=abi/5.5.0)",
  "code": "UnhandledRejection",
  "details": {
    "name": "Error",
    "reason": "no matching function",
    "code": "INVALID_ARGUMENT",
    "argument": "sighash",
    "value": "0xac9650d8"
  }
}
```

Note that the error specifies the sighash of the first pending transaction on the safe.
In your case, @rudolfs, it was `addOwnerWithThreshold(address,uint256)`, in my case it is `multicall(bytes[])`.

So this makes me think the radicle app is querying the safe transaction service to see if there are any relevant transactions in queue and then throwing an error if it doesn't recognize the sighash.

I will try clearing the queue of transactions and see if that resolves the issue.

**Comment by auryn-macmillan** [comment]
Clearing out the queued transaction solved the issue.

**Comment by Kaihuang724** [comment]
Closing this as orgs will not be implemented for MVP
