### ISSUE TITLE
'no storage space' Error when trying to install Radical Upstream

### ISSUE THREAD

**Issue by christroutner** [radicle-dev/radicle-upstream#2743]
I just downloaded `radicle-upstream-0.2.13.AppImage` for 64-bit Ubuntu Linux, and got an error when trying to set up an account. Despite the error below, I have plenty of storage space on my computer.

Here is the error displayed in the Radicle Upstream app:
```
{
  "stack": "Error: Could not create identity\n    at file:///tmp/.mount_radiclAJVzzh/resources/app.asar/public/bundle.js:50:187848\n    at async l (file:///tmp/.mount_radiclAJVzzh/resources/app.asar/public/bundle.js:50:187540)",
  "message": "Could not create identity",
  "code": "IdentityCreationFailure",
  "details": {
    "handle": "trout"
  },
  "source": {
    "stack": "TypeError: Failed to fetch\n    at Zt.fetch (file:///tmp/.mount_radiclAJVzzh/resources/app.asar/public/bundle.js:1:1650401)\n    at Zt.fetchOk (file:///tmp/.mount_radiclAJVzzh/resources/app.asar/public/bundle.js:1:1649923)\n    at yt.create (file:///tmp/.mount_radiclAJVzzh/resources/app.asar/public/bundle.js:1:1644066)\n    at file:///tmp/.mount_radiclAJVzzh/resources/app.asar/public/bundle.js:50:187746\n    at d (file:///tmp/.mount_radiclAJVzzh/resources/app.asar/public/bundle.js:1:1591826)\n    at async file:///tmp/.mount_radiclAJVzzh/resources/app.asar/public/bundle.js:50:187629\n    at async l (file:///tmp/.mount_radiclAJVzzh/resources/app.asar/public/bundle.js:50:187540)",
    "message": "Failed to fetch",
    "code": "UnknownException",
    "details": {
      "name": "TypeError"
    }
  }
}
```

Here is the error displayed in the command line:
```
trout@trout-dev:~/Downloads$ ./radicle-upstream-0.2.13.AppImage 
2022-02-05T16:55:22.412707Z  INFO api::git_helper: copied git remote helper binary destination="/home/trout/.radicle/bin/git-remote-rad"
2022-02-05T16:55:23.747275Z  INFO proxy::http: GET /v1/session 404 elapsed=28.7531ms
2022-02-05T16:55:37.940799Z  INFO proxy::http: POST /v1/keystore 204 elapsed=229.919931ms
2022-02-05T16:55:37.946268Z  INFO api::process: reloading
Error: failed to initialize radicle_daemon peer

Caused by:
    no storage space

Stack backtrace:
   0: api::peer::create
   1: api::process::run::{{closure}}
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: tokio::park::thread::CachedParkThread::block_on
   4: tokio::runtime::thread_pool::ThreadPool::block_on
   5: tokio::runtime::Runtime::block_on
   6: radicle_proxy::main
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: std::rt::lang_start::{{closure}}
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/core/src/ops/function.rs:259:13
  10: std::panicking::try::do_call
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:406:40
  11: std::panicking::try
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:370:19
  12: std::panic::catch_unwind
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panic.rs:133:14
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/rt.rs:128:48
  14: std::panicking::try::do_call
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:406:40
  15: std::panicking::try
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:370:19
  16: std::panic::catch_unwind
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panic.rs:133:14
  17: std::rt::lang_start_internal
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/rt.rs:128:20
  18: main
  19: __libc_start_main
  20: _start

```

**Comment by christroutner** [comment]
Thanks for pointing out those directories. After deleting them, then retrying with the AppImage, I got Upstream to run correctly.

It would be a good idea to add troubleshooting information somewhere. Maybe this Issue is it. Just knowing that I needed to delete those directories and re-run the app is all I needed to fix the issue.
