### ISSUE TITLE
A JavaScript error occurred in the main process Uncaught Exception: Error: invalid number of arguments on Linux

### ISSUE THREAD

**Issue by talentlessguy** [radicle-dev/radicle-upstream#2808]
- Upstream version: 0.2.14
- Electron 17.1

When I try to launch Upstream on Linux, I get this:

```
➜ /home/v1rtl/Applications/radicle-upstream-0.2.14_8676b7436a0c913e40047708a5c3ef70.AppImage --no-sandbox %U
A JavaScript error occurred in the main process
Uncaught Exception:
Error: invalid number of arguments
    at parseArgs (/tmp/.mount_radicloLAqyf/resources/app.asar/native/bundle.js:43374:15)
    at /tmp/.mount_radicloLAqyf/resources/app.asar/native/bundle.js:43119:14
    at /tmp/.mount_radicloLAqyf/resources/app.asar/native/bundle.js:43378:3
    at Object.<anonymous> (/tmp/.mount_radicloLAqyf/resources/app.asar/native/bundle.js:43380:12)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (node:electron/js2c/browser_init:189:3197)
[291490:0415/172647.855464:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
^C⏎      
```

**Comment by geigerzaehler** [comment]
Thanks for reporting this @talentlessguy. It looks like our command line parsing is not able to deal with options passed to the AppImage executor. We’ll fix this. In the meantime, you can remove the `--no-sandbox` options.
