### ISSUE TITLE
Server side events stop working after some time

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2842]
After having Upstream open for a while, it stops automatically refreshing the UI on monorepo updates.
Don't have step-by-step repro yet.

**Comment by rudolfs** [comment]
Seeing this error:
```
error.ts:177 Error: Received proxy peer event
    at localPeer.ts:48:13
    at Bacon.mjs:473:29
    at Jt (Bacon.mjs:362:21)
    at Object.inTransaction (Bacon.mjs:451:13)
    at Pr.push (Bacon.mjs:2270:30)
    at Pr.handleEvent (Bacon.mjs:2329:25)
    at Bacon.mjs:34:36
    at Bacon.mjs:2593:28
    at Bacon.mjs:1913:25
    at EventSource.<anonymous> (events.ts:182:7) Object
Ui @ error.ts:177
127.0.0.1:17246/v1/notifications/local_peer_events:1          Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
```

**Comment by geigerzaehler** [comment]
Maybe this is caused by suspending the system.

**Comment by rudolfs** [comment]
> Maybe this is caused by suspending the system.

I'm pretty sure I've noticed this during normal operation as well.
